### PR TITLE
Admin

### PR DESCRIPTION
**Pull request by torvista**

### CODE REVIEW

**Comment by lat9** [comment]
Noting that many of the updates provided (especially in the javascript) are no longer needed, since #30 has removed that helper function.

I'll review the other changes for incorporation in v4.0.0.

**Review by lat9 — COMMENTED** [review]
I'm not seeing a condition where that sort could return `false`, since code leading up to that sort has guaranteed that `$sitemapFiles` is an array (which could be empty).

**Comment by torvista** [comment]
>I'm not seeing a condition where that sort could return false, 

No, agreed,

**Comment by lat9** [comment]
Closing this PR; all issues corrected here have been incorporated into the forthcoming v4.0.0 release.

**Pull request closed without merging**
